# To set up SonarCloud follow
# https://github.com/DEFRA/cdp-documentation/blob/main/howto/sonarcloud.md

sonar.projectKey=DEFRA_waste-manage-account-frontend
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/waste-manage-account-frontend
sonar.links.ci=https://github.com/DEFRA/waste-manage-account-frontend/actions
sonar.links.scm=https://github.com/DEFRA/waste-manage-account-frontend
sonar.links.issue=https://github.com/DEFRA/waste-manage-account-frontend/issues

sonar.sources=src/
sonar.exclusions=src/**/*.test.js
sonar.tests=src/,test/
sonar.test.inclusions=src/**/*.test.js,test/**/*.test.js

sonar.cpd.exclusions=src/**/*.test.js

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
