services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:24-bookworm
    volumes:
      - ..:/workspaces/waste-manage-account-frontend:cached
    command: sleep infinity
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    restart: unless-stopped
    networks:
      - cdp-tenant

networks:
  cdp-tenant:
    driver: bridge
